
// ===============================================================================
// CUSTOM TOOLTIP GENERATED BY AI, WASN'T USE IN THS PROJECT
// ===============================================================================

import { motion } from "framer-motion";

interface TooltipProps {
  children: React.ReactNode;
  text: string;
  position?: "top" | "bottom" | "left" | "right";
}

const Tooltip: React.FC<TooltipProps> = ({ children, text, position = "top" }) => {
  return (
    <div className="relative group cursor-pointer">
      {/* Element to hover */}
      {children}

      {/* Tooltip */}
      <motion.div
        initial={{ opacity: 0, y: position === "top" ? 5 : -5 }}
        animate={{ opacity: 1, y: 0 }}
        exit={{ opacity: 0, y: position === "top" ? 5 : -5 }}
        transition={{ duration: 0.2 }}
        className={`absolute whitespace-nowrap bg-gray-800 text-white text-xs px-2 py-1 rounded-md opacity-0 
          group-hover:opacity-100 transition-all duration-300 pointer-events-none
          ${position === "top" ? "bottom-full left-1/2 -translate-x-1/2 mb-2" : ""}
          ${position === "bottom" ? "top-full left-1/2 -translate-x-1/2 mt-2" : ""}
          ${position === "left" ? "right-full top-1/2 -translate-y-1/2 mr-2" : ""}
          ${position === "right" ? "left-full top-1/2 -translate-y-1/2 ml-2" : ""}`}
      >
        {text}
        {/* Tooltip Arrow */}
        <div
          className={`absolute w-2 h-2 bg-gray-800 rotate-45
            ${position === "top" ? "left-1/2 -translate-x-1/2 top-full" : ""}
            ${position === "bottom" ? "left-1/2 -translate-x-1/2 bottom-full" : ""}
            ${position === "left" ? "right-0 top-1/2 -translate-y-1/2" : ""}
            ${position === "right" ? "left-0 top-1/2 -translate-y-1/2" : ""}`}
        ></div>
      </motion.div>
    </div>
  );
};

export default Tooltip;
